# Generated by Django 5.2.6 on 2025-10-09 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaPsicologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_horario', models.DateTimeField()),
                ('status', models.CharField(choices=[('livre', 'Livre'), ('reservado', 'Reservado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado'), ('bloqueado', 'Bloqueado')], default='livre', max_length=20)),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.psicologo')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidade', models.CharField(choices=[('online', 'Online'), ('presencial', 'Presencial')], max_length=20)),
                ('status', models.CharField(choices=[('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('concluido', 'Concluído')], default='confirmado', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('agenda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='psiacesso_main.agendapsicologo')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.paciente')),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.psicologo')),
            ],
        ),
        migrations.CreateModel(
            name='AnotacaoPsicologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.psicologo')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psiacesso_main.consulta')),
            ],
        ),
        migrations.CreateModel(
            name='DisponibilidadePsicologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Domingo'), (1, 'Segunda'), (2, 'Terça'), (3, 'Quarta'), (4, 'Quinta'), (5, 'Sexta'), (6, 'Sábado')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('intervalo_minutos', models.PositiveIntegerField(default=50)),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.psicologo')),
            ],
        ),
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.IntegerField(choices=[(0, 'ACADEMICA'), (1, 'CURSO')])),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.psicologo')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveIntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.paciente')),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.psicologo')),
            ],
            options={
                'unique_together': {('paciente', 'psicologo')},
            },
        ),
    ]
